### ISSUE TITLE
Have you tried GFlownet on MATH/GSM8K?

### ISSUE THREAD

**Issue by linyongver** [Yu-Fangxu/FoR#3]
Have you tried GFlownet on MATH/GSM8K?

**Comment by Yu-Fangxu** [comment]
Hi, we have not yet tried GFlowNet on GSM8K, which is a free-form reasoning problem. Current work only focuses on those problems with restricted action space. Extending GFlowNet to more general reasoning/planning tasks is a promising exploration direction. Our future work will explore this topic.

Thanks for your question and attention!
