### ISSUE TITLE
Using llama model with openai

### ISSUE THREAD

**Issue by 4adex** [Yu-Fangxu/FoR#4]
I was trying to analyse the code and replicate the results.
The `query_LM` function in `lightning_module_selection.py` of GSM8k, it uses openAI but declares model as `meta-llama/Llama-3-8B`, is it possible to do so? Is this exactly what was used while generating the result?
https://github.com/Yu-Fangxu/FoR/blob/ce392e91b2caf207b7034580fef034d14b3f4613/GSM8K/lightning_module_selection.py#L910-L916

**Comment by Yu-Fangxu** [comment]
Thanks for your attention and question!
Yes, it is possible because we're using vLLM to speed up the inference, you could refer to vLLM document https://docs.vllm.ai/en/latest/getting_started/examples/openai_chat_completion_client.html to find more details.

**Comment by 4adex** [comment]
Thanks a lot for quick response :)
